Repository Applion-11th/Applion-Client, pull requests merged in 2023-02, with the labels that each got.

#22 Chore/modify styles
  src/App.js
  src/assets/logoFullApply.svg
  src/assets/logoPlaceHolder.svg
  src/assets/placeHolder.svg
  src/components/Header/index.js
  src/components/InputApply/index.js
  src/components/Radio/index.js
  src/components/atoms/InputSmall/index.js
  src/components/atoms/index.js
  src/components/index.js
  src/pages/Application.js
  src/pages/Complete.js
  src/pages/Info.js
  src/pages/Register.js
Labels: feature

#23 Fix/main page
  src/pages/Main.js
Labels: fix

#24 fix: make privacy agreement required
  src/pages/Info.js
  src/pages/Register.js
Labels: fix

#31 Refactor/submit
  src/components/SelectTrack/index.js
  src/components/atoms/DisplayTime/Pretendard-Regular.otf
  src/components/atoms/Input/index.js
  src/components/atoms/InputPwd/index.js
  src/components/atoms/InputSmall/index.js
  src/pages/Application.js
  src/pages/Info.js
  src/pages/Login.js
  src/pages/Register.js
Labels: feature, refactor

#32 Feat/connect be
  .gitignore
  src/components/atoms/Input/index.js
  src/components/atoms/InputPwd/index.js
  src/pages/Application.js
  src/pages/Info.js
  src/pages/Login.js
  src/pages/Register.js
Labels: documentation, feature

#54 Feat/remove email
  src/components/atoms/Modal/index 2.js
  src/pages/Login.js
  src/pages/Main.js
  src/pages/Register.js
Labels: fix, feature, API

#58 Feat: make header fixed and apply linear gradient
  src/components/Header/index.js
  src/pages/Main.js
Labels: bug, feature

#55 Feat/info api
  src/components/SelectTrack/index.js
  src/pages/Info.js
Labels: feature, API

#60 Feat/main
  package-lock.json
  package.json
  public/model.glb
  src/App.js
  src/components/Model.js
  src/components/Overlay.js
  src/pages/Main.js
  src/pages/Test.js
  src/styles/styles.css
Labels: feature, refactor

#62 feat: apply new animation to main page
  src/App.js
  src/assets/logoFull.svg
  src/assets/logoFullApply.svg
  src/assets/mainanimation.mkv
  src/assets/mainanimation.mp4
  src/components/Model/index.js
  src/components/Overlay/index.js
  src/components/index.js
  src/pages/Main.js
  src/pages/Test.js
Labels: fix, feature

#64 Feat/design modify
  src/assets/logoFullApplySmall.svg
  src/components/Header/index.js
  src/components/Overlay/index.js
  src/pages/Application.js
Labels: chore

#65 Feat/info req
  src/components/SelectTrack/index.js
  src/pages/Info.js
Labels: fix, feature

#78 fix: change logo width to vw
  src/App.js
  src/components/Overlay/index.js
Labels: feature

#82 chore: change favicon and title
  public/favicon.ico
  public/index.html
Labels: chore

#83 fix: make register button gray when not filled
  src/pages/Register.js
Labels: fix

#84 fix: remove double scroll issue
  src/components/Header/index.js
  src/components/Overlay/index.js
Labels: fix

#86 Refactor/logout
  src/components/Header/index.js
  src/pages/Kakao.js
  src/pages/Login.js
Labels: fix, refactor, API

#87 Feat/debug info
  src/components/InputApply/index.js
  src/components/SelectTrack/index.js
  src/pages/Application.js
  src/pages/Info.js
Labels: fix

#94 feat: change question track name depending on track type
  src/pages/Application.js
  src/pages/Info.js
Labels: feature

#95 feat: align text in /complete to center
  src/pages/Complete.js
Labels: chore

#96 feat: change font size of TextboxBold
  src/components/Overlay/index.js
Labels: chore

#101 fix: make button clickable when conditions satisfied
  src/pages/Register.js
Labels: fix
